//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LKBSS.rc
//
#define IDB_RecordNewMed                2
#define ID_save                         2
#define IDOK2                           2
#define IDC_ScanHardware                3
#define IDB_EditMed                     3
#define IDB_AddMedicine                 3
#define IDB_OnceDispensing              3
#define IDOK3                           3
#define IDB_DelMed                      4
#define IDB_PrintPres                   4
#define IDB_DeleteMedicine              4
#define IDOK4                           4
#define IDB_Print                       5
#define IDB_DeletePres                  5
#define IDB_EditMedicine                5
#define IDB_Close                       6
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LKBSS_DIALOG                102
#define IDS_DialogRes                   102
#define IDS_ControlRes                  103
#define IDS_MedPictureRes               103
#define IDS_Caption                     104
#define IDS_LogOff                      105
#define IDS_StopDistrubting             106
#define IDS_StartDistrubting            107
#define IDS_LocationUsable              108
#define IDS_LocationDisable             109
#define IDS_HIS                         110
#define IDS_OPERATOR                    111
#define IDS_ADMINISTRATOR               112
#define IDS_SUPER_ADMINISTRATOR         113
#define IDS_Setting                     114
#define IDS_BasicSetting                115
#define IDS_PLC                         116
#define IDS_Database                    117
#define IDS_Print                       118
#define IDS_SysMonitor                  119
#define IDS_erPswConfirm                120
#define IDS_erUserInfo                  121
#define IDS_erInfo                      121
#define IDS_succAddUser                 122
#define IDS_errAddUser                  122
#define IDS_erUserExisted               123
#define IDS_Failed                      124
#define IDS_DeleteConfirm               125
#define IDS_NoIKey                      126
#define IDS_Tablet                      127
#define IDR_MAINFRAME                   128
#define IDS_Box                         128
#define IDD_WorkQueue                   129
#define IDS_Injection                   129
#define IDD_DetailInfo                  130
#define IDS_Other                       130
#define IDD_ModifyPW                    131
#define IDS_Pre_ST_unsettled            131
#define IDS_Pre_ST_settled              132
#define IDD_AddNewUser                  133
#define IDS_Pre_ST_failed               133
#define IDD_PrescriptionInfo            134
#define IDS_Pre_SC_HIS                  134
#define IDD_UserManager                 135
#define IDS_Pre_SC_manual               135
#define IDR_MAINMENU                    136
#define IDS_Pre_SC_batch                136
#define IDD_DOSEMONITOR                 137
#define IDS_Pre_Type_other              137
#define IDD_DEVICEMONITOR               138
#define IDS_Pre_Type_clinic             138
#define IDD_Login                       139
#define IDS_Pre_Type_Hos                139
#define IDD_StopDistributeMed           140
#define IDS_patient_sex_male            140
#define IDD_LogOff                      141
#define IDS_patient_sex_female          141
#define IDD_AddMedcine                  142
#define IDS_patient_sex_unknow          142
#define IDD_AddMed_InfoZone             143
#define IDS_SUCC                        143
#define IDD_AddMed_OpZone               144
#define IDS_StartFilling                144
#define IDD_MessageBox                  145
#define IDS_FinishFilling               145
#define IDD_ModifyUser                  146
#define IDS_Pre_Med_exist               146
#define IDD_SystemConfig                147
#define IDS_Pre_ST_waitting             147
#define IDD_MedicineMgr                 148
#define IDD_QueryMedicine               148
#define IDS_Pre_ST_invalidated          148
#define IDD_MedicineInfo                149
#define IDS_CHOOSE_ROW                  149
#define IDD_CreatePrescription          150
#define IDD_PrescriptInfo               150
#define IDS_errUserName                 150
#define IDD_AddPharmacy                 151
#define IDS_errUserPsw                  151
#define IDD_QueryPrescript              152
#define IDS_errUserIKey                 152
#define IDD_PrescriptInfo_ReadOnly      153
#define IDS_errSecurity                 153
#define IDD_Statistics                  154
#define IDS_SwitchUser                  154
#define IDD_LogViewer                   155
#define IDS_NoBind                      155
#define IDS_erDate                      156
#define IDD_BatImport                   157
#define IDS_resetDefault                157
#define IDB_SL_CHANNEL                  158
#define IDS_resetConfirm                158
#define IDS_saveConfirm                 159
#define IDB_SL_CHANNEL_ACTIVE           160
#define IDS_noMed                       160
#define IDB_SL_THUMB                    161
#define IDS_erInt                       161
#define IDB_SL_THUMB_ACTIVE             162
#define IDS_Pre_waittingOrInvalidated   162
#define IDS_configEnd                   163
#define IDB_COLUMNHEADER_SPAN           164
#define IDB_COLUMNHEADER_START          165
#define IDB_COLUMNHEADER_END            166
#define IDB_HORIZONTAL_SCROLLBAR_RIGHTARROW 167
#define IDB_HORIZONTAL_SCROLLBAR_SPAN   168
#define IDB_HORIZONTAL_SCROLLBAR_LEFTARROW 169
#define IDB_VERTICLE_SCROLLBAR_UPARROW  170
#define IDB_VERTICLE_SCROLLBAR_SPAN     171
#define IDB_VERTICLE_SCROLLBAR_THUMB    172
#define IDB_VERTICLE_SCROLLBAR_DOWNARROW 173
#define IDB_VERTICLE_SCROLLBAR_TOP      174
#define IDB_VERTICLE_SCROLLBAR_BOTTOM   175
#define IDB_HORIZONTAL_SCROLLBAR_THUMB  176
#define IDD_MedAddrEditor               177
#define IDB_FOLDER_TITLE_BK             178
#define IDD_SysSetting                  179
#define IDD_Setting_BasicSetting        180
#define IDD_Setting_PLC                 181
#define IDD_Setting_Printer             182
#define IDD_Setting_SysMonitor          183
#define IDD_Setting_Database            184
#define IDD_CheckNeed                   185
#define IDD_DIALOG1                     187
#define IDD_Setting_ResetDefault        187
#define IDB_BITMAP1                     190
#define IDD_DOSEMONITOR1                192
#define IDD_DEVICEMONITOR1              193
#define IDD_DOSEMONITOR3                194
#define IDD_DOSEMONITOR2                195
#define IDD_ResumeBox                   198
#define IDD_DOSEMONITOR4                199
#define IDD_DOSEMONITOR5                200
#define IDD_DOSEMONITOR6                201
#define IDD_DOSEMONITOR7                202
#define IDD_DOSEMONITOR8                203
#define IDD_Keyboard                    204
#define IDD_MedLocationEditor           205
#define IDD_DIALOG2                     206
#define IDD_SENDMED                     206
#define IDD_DLG_ADDMED                  208
#define IDD_DLG_MEDMANAGER              209
#define IDD_DLG_PRESCINFO               210
#define IDC_QueryPrescription           1000
#define IDC_Help                        1001
#define IDC_StartMedicine               1002
#define IDC_StopMedicine                1003
#define IDC_AddMedicine                 1004
#define IDC_QueryMedicine               1005
#define IDC_WorkQueue_LeftList          1007
#define IDC_WorkQueue_RightList         1008
#define IDC_MoveRight                   1009
#define IDC_MoveLeft                    1010
#define IDC_MoveUp                      1011
#define IDC_MoveDown                    1012
#define IDC_CHECK_StopScroll            1013
#define IDC_EDIT1                       1014
#define IDC_Move_Left_All               1014
#define IDC_EDIT2                       1015
#define IDC_EDIT3                       1016
#define IDC_EDIT4                       1017
#define IDC_EDIT5                       1018
#define IDC_CHECK1                      1019
#define IDC_EDIT7                       1019
#define IDC_CHECK2                      1020
#define IDC_EDIT8                       1020
#define IDC_CHECK3                      1021
#define IDC_EDIT9                       1021
#define IDC_EDIT6                       1022
#define IDC_EDIT10                      1022
#define IDC_BUTTON1                     1023
#define IDC_EDIT11                      1023
#define IDC_BUTTON2                     1024
#define IDC_EDIT12                      1024
#define IDC_BUTTON8                     1025
#define IDC_COMBO1                      1025
#define IDC_CreateUser                  1025
#define IDC_EDIT13                      1025
#define IDC_COMBO2                      1026
#define IDC_ModifyPW                    1026
#define IDC_EDIT14                      1026
#define IDC_BUTTON10                    1026
#define IDC_BTN_EXIT_SEND               1026
#define IDC_COMBO3                      1027
#define IDC_BUTTON11                    1027
#define IDC_EDIT22                      1027
#define IDC_COMBO4                      1028
#define IDC_Close                       1028
#define IDC_BUTTON12                    1028
#define IDC_COMBO5                      1029
#define IDC_BUTTON13                    1029
#define IDC_COMBO6                      1030
#define IDC_BUTTON14                    1030
#define IDC_LIST1                       1031
#define IDC_EDIT16                      1031
#define IDC_BUTTON15                    1031
#define IDC_BUTTON4                     1032
#define IDC_EDIT17                      1032
#define IDC_listMedLocation             1032
#define IDC_BUTTON16                    1032
#define IDC_BUTTON5                     1033
#define IDC_AssocPrescripList           1033
#define IDC_EDIT18                      1033
#define IDC_listAcceRunningState        1033
#define IDC_BUTTON6                     1034
#define IDC_AddrList_SimilarDrugs       1034
#define IDC_BUTTON7                     1035
#define IDC_Login                       1035
#define IDC_BUTTON20                    1035
#define IDC_UKeyID                      1036
#define IDC_iKey                        1036
#define IDC_BUTTON21                    1036
#define IDC_Cancle                      1037
#define IDC_BUTTON22                    1037
#define IDC_SkipPos                     1038
#define IDC_BUTTON23                    1038
#define IDC_SkipMed                     1039
#define IDC_BUTTON24                    1039
#define IDC_ExitAdd                     1040
#define IDC_BUTTON25                    1040
#define IDC_MedInfo                     1041
#define IDC_StartAdd                    1041
#define IDC_BUTTON26                    1041
#define IDC_Subtract                    1042
#define IDC_BUTTON27                    1042
#define IDC_Plus                        1043
#define IDC_BUTTON28                    1043
#define IDC_BUTTON29                    1044
#define IDC_Subtract2                   1044
#define IDC_Plus2                       1045
#define IDC_BUTTON30                    1045
#define IDC_AddNewUser                  1046
#define IDC_Subtract3                   1046
#define IDC_BUTTON31                    1046
#define IDC_ModifyUser                  1047
#define IDC_Plus3                       1047
#define IDC_BUTTON32                    1047
#define IDC_DelUser                     1048
#define IDC_Subtract4                   1048
#define IDC_BUTTON33                    1048
#define IDC_UserList                    1049
#define IDC_Plus4                       1049
#define IDC_BUTTON34                    1049
#define IDC_UserGroup                   1050
#define IDC_BUTTON35                    1050
#define IDC_StUserGruop                 1051
#define IDC_BUTTON36                    1051
#define IDC_StUserList                  1052
#define IDC_BUTTON37                    1052
#define IDC_BindUKey                    1053
#define IDC_BUTTON38                    1053
#define IDC_Undo                        1054
#define IDC_BUTTON39                    1054
#define IDC_CHECK4                      1055
#define IDC_BUTTON40                    1055
#define IDC_CHECK5                      1056
#define IDC_BUTTON41                    1056
#define IDC_listSystem                  1057
#define IDC_BUTTON42                    1057
#define IDB_WatchMed                    1058
#define IDC_BUTTON43                    1058
#define IDC_QueryMed                    1059
#define IDC_BUTTON44                    1059
#define IDC_listMedInfo                 1060
#define IDC_BUTTON45                    1060
#define IDC_RADIO1                      1061
#define IDB_PanDian                     1061
#define IDC_BUTTON46                    1061
#define IDC_RADIO2                      1062
#define IDC_BUTTON47                    1062
#define IDB_PanDian2                    1062
#define IDC_RADIO3                      1063
#define IDC_BUTTON48                    1063
#define IDC_RADIO4                      1064
#define IDC_BUTTON49                    1064
#define IDC_RADIO5                      1065
#define IDC_BUTTON50                    1065
#define IDC_RADIO6                      1066
#define IDC_BUTTON51                    1066
#define IDC_EDIT15                      1067
#define IDC_SLIDER1                     1068
#define IDC_BUTTON3                     1069
#define IDC_PROGRESS1                   1070
#define IDC_PrescriptInfo               1071
#define IDC_PatientInfo                 1072
#define IDC_COMBO7                      1073
#define IDC_COMBO8                      1074
#define IDC_listPrescript               1075
#define IDC_Query                       1076
#define IDC_listCommonMed               1077
#define IDB_ViewPres                    1078
#define IDB_CreatePres                  1079
#define IDC_listPresInfo                1080
#define IDC_listMedCategories           1081
#define IDB_EditPres                    1081
#define IDB_ViewLog                     1082
#define IDC_listLogRecord               1083
#define IDB_Import                      1086
#define IDB_Browse                      1087
#define IDB_Open                        1088
#define IDC_listContent                 1089
#define IDC_EditAddr                    1090
#define IDC_Text                        1091
#define IDC_Slider_Warning              1092
#define IDC_AddMedList                  1093
#define IDC_EDIT_NUM                    1094
#define IDC_OK                          1095
#define IDC_EDIT_NUM2                   1095
#define IDC_CANCEL                      1096
#define IDC_EDIT_NUM3                   1096
#define IDC_TREEGROUP                   1097
#define IDC_EDIT_NUM4                   1097
#define IDC_WarnPercent                 1098
#define IDC_LIST2                       1103
#define IDC_CLEARLOCATION               1104
#define IDC_LISTDEVICE                  1104
#define IDC_STATIC1                     1105
#define IDC_STATIC2                     1106
#define IDC_STATIC3                     1107
#define IDC_STATIC4                     1108
#define IDC_STATIC5                     1109
#define IDC_STATIC6                     1110
#define IDC_STATIC7                     1111
#define IDC_STATIC8                     1112
#define IDC_STATIC9                     1113
#define IDC_STATIC10                    1114
#define IDC_STATIC11                    1115
#define IDC_ALLSelect                   1116
#define IDC_NotSelect                   1117
#define IDC_CHK_BindiKey                1119
#define IDC_EDT_                        1120
#define IDC_EDT_usrName                 1120
#define IDC_EDT_stationNum              1120
#define IDC_EDT_dealFrequency           1120
#define IDC_EDT_ThermalPrtPort          1120
#define IDC_EDT_hint                    1121
#define IDC_EDT_psw                     1122
#define IDC_EDT_psw_confirm             1123
#define IDC_EDT_usrRealName             1124
#define IDC_EDT_userName                1124
#define IDC_EDT_userRealName            1125
#define IDC_CMB_Group                   1126
#define IDC_EDT_OldPSW                  1127
#define IDC_EDT_NewPSW                  1128
#define IDC_EDT_ConfirmPSW              1129
#define IDC_APPLY                       1139
#define IDC_EDT_IP                      1140
#define IDC_EDT_conTimeOut              1141
#define IDC_LocationId                  1142
#define IDC_MedicineName                1143
#define IDC_MedicineType                1144
#define IDC_MaxCapacity                 1145
#define IDC_CurCapacity                 1146
#define IDC_P                           1147
#define IDC_EDT_log                     1148
#define IDC_EDT_server                  1149
#define IDC_EDT_user                    1150
#define IDC_EDT_database                1151
#define IDC_EDT_port                    1152
#define IDC_EDT_ThermalPrtBaud          1153
#define IDC_EDT_ThermalPrtPaper         1154
#define IDC_EDT_SatoPrtPort             1155
#define IDC_EDT_SatoPrtBaud             1156
#define IDC_EDT_BoxFrequency            1157
#define IDC_EDT_DeviceFrequency         1158
#define IDC_CMB_HIS                     1159
#define IDC_CMB_department              1160
#define IDC_CMB_patientName             1161
#define IDC_CMB_source                  1162
#define IDC_DTPR_begin                  1163
#define IDC_DTPR_end                    1164
#define IDC_CHK_date                    1166
#define IDC_STC_preId                   1167
#define IDC_STC_HIS_preId               1168
#define IDC_STC_departmentId            1169
#define IDC_STC_departmentName          1170
#define IDC_STC_state                   1171
#define IDC_STC_fetchWindow             1172
#define IDC_STC_validateTime            1173
#define IDC_STC_doctorId                1174
#define IDC_STC_doctorName              1175
#define IDC_STC_source                  1176
#define IDC_STC_type                    1177
#define IDC_STC_priority                1178
#define IDC_STC_create_time             1179
#define IDC_STC_patientName             1180
#define IDC_STC_patientENName           1181
#define IDC_STC_In_id                   1182
#define IDC_STC_sex                     1183
#define IDC_STC_age                     1184
#define IDC_STC_patientType             1185
#define IDC_STC_bedId                   1186
#define IDC_STC_last_distribute_time    1187
#define IDC_EDIT1_my                    1189
#define IDC_DATETIMEPICKER1             1192
#define IDC_CMB_characterSet            1193
#define IDC_listMedicine                1194
#define IDC_EDT_preId                   1195
#define IDC_EDT_preHISId                1196
#define IDC_STC_medList                 1197
#define IDC_CHK_prescription            1198
#define IDC_EDT_name                    1200
#define IDC_real_name                   1201
#define IDC_name                        1202
#define IDC_realName                    1204
#define IDC_grp_caption                 1206
#define IDC_grp_caption2                1207
#define IDC_STATIC13                    1210
#define IDC_CHK_medValidate             1211
#define IDC_EDIT19                      1212
#define IDC_STATIC12                    1214
#define IDC_EDIT20                      1215
#define IDC_EDIT21                      1216
#define IDC_EDIT_medName                1217
#define IDC_FULLFILL1                   1218
#define IDC_FULLFILL2                   1219
#define IDC_FULLFILL3                   1220
#define IDC_FULLFILL4                   1221
#define IDC_BatchNo1                    1222
#define IDC_ValiDate1                   1223
#define IDC_BatchNo2                    1224
#define IDC_ACTFXCPU1                   1224
#define IDC_ValiDate2                   1225
#define IDC_BTN_CANCEL                  1225
#define IDC_BatchNo3                    1226
#define IDC_BTN_BACK                    1226
#define IDC_BTN_VIEW                    1226
#define IDC_ValiDate3                   1227
#define IDC_BTN_ADDSTART                1227
#define IDC_BTN_EDIT                    1227
#define IDC_BatchNo4                    1228
#define IDC_BTN_UPDATE                  1228
#define IDC_ValiDate4                   1229
#define IDC_BTN_EXIT                    1229
#define IDC_BTN_JUMPMED                 1230
#define IDC_BTN_JUMPLOC                 1231
#define IDC_BTN_STARSENDMED             1232
#define IDC_CHECK6                      1235
#define IDC_BTN_STAR_SEND               1237
#define IDC_BTN_END_SEND                1238
#define IDC_LIST_MEDINFO                1239
#define IDC_STATIC_PRESCNO              1240
#define IDC_STATIC_PRESCTYPE            1241
#define IDC_STATIC_STATE                1242
#define IDC_STATIC_DOCNO                1243
#define IDC_STATIC_DOCNAME              1244
#define IDC_STATIC_ROOMNAME             1245
#define IDC_STATIC_WINDOWNO             1246
#define IDC_STATIC_PATIENTNO            1247
#define IDC_STATIC_PATIENT_NAME         1248
#define IDC_STATIC_PATIENT_SEX          1249
#define IDC_STATIC_HOME_NO              1250
#define IDC_STATIC_BEDNO                1251
#define IDC_BTN_MIN                     1252
#define IDC_BTN_CLOSE                   1253
#define IDC_STATIC_FSHOW                1254
#define IDC_STATIC_SSHOW                1255
#define IDC_LISTMED                     1256
#define IDC_BUTSTART                    1257
#define IDC_BUTSTOP                     1258
#define IDC_BUTBACK                     1259
#define IDC_STATGROUP                   1260
#define IDC_PATIENT                     1261
#define IDC_SEX                         1262
#define IDC_AGE                         1263
#define IDC_BED                         1264
#define IDC_TIME                        1265
#define IDC_CHECKLACK                   1266
#define IDC_COMBO                       1267
#define IDC_CHECKSTOP                   1268
#define IDC_CHECKALL                    1268
#define IDC_CHECKEMPORT                 1269
#define IDC_CHECKBOX                    1269
#define IDC_CHECKMEDSTATE               1270
#define IDC_CHECKLACKMED                1271
#define IDC_BUTOPEN                     1272
#define IDC_DATETIMEPICKER2             1275
#define IDC_STATICMEDCOUNT              1276
#define IDM_AddMedicine                 32771
#define IDM_StartMedicine               32772
#define IDM_SendMed                     32772
#define IDM_LogOff                      32773
#define IDM_SwitchUser                  32774
#define IDM_LogOut                      32775
#define IDM_RecordPres                  32776
#define IDM_QueryPres                   32777
#define IDM_Statistics                  32778
#define IDM_QueryLog                    32779
#define IDM_QueryMed                    32780
#define IDM_BatchImportPres             32783
#define IDM_BatchImportMedInfo          32784
#define IDM_UserManage                  32785
#define IDM_PrescriptionManage          32786
#define IDM_MedManage                   32787
#define IDM_HelpDoc                     32788
#define IDM_About                       32789
#define IDM_Contact                     32790
#define IDM_SystemSetting               32791
#define IDM_Reboot                      32792
#define IDM_Urgency                     32794
#define IDM_StopMedicine                32795
#define IDM_Monitor                     32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1277
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
